/**
 * MissionTemplates — Static data for external missions.
 *
 * Cultists can be sent on missions outside the compound for various rewards:
 *   - Heat reduction: lower the heat stat
 *   - PR generation: increase follower quality / reputation
 *   - Object acquisition: obtain decor/ornaments (generates heat)
 *   - Resource gathering: earn money and influence
 *
 * Each mission has a difficulty (1-10), duration (in-game hours),
 * min/max cultist count, and random events with skill-check choices.
 *
 * Refer to docs/gameplay-design-reference.md §10 Missions System for design details.
 */

export type MissionType =
  | 'heat_reduction'
  | 'pr_generation'
  | 'object_acquisition'
  | 'resource_gathering';

export interface MissionTemplate {
  id: string;
  name: string;
  type: MissionType;
  description: string;
  /** Duration in in-game hours */
  duration: number;
  /** Difficulty 1-10 */
  difficulty: number;
  rewards: {
    heatReduction?: number;
    prGain?: number;
    money?: number;
    influence?: number;
    /** Decor item ID from DecorItems data */
    decorItemId?: string;
  };
  /** Heat generated by running this mission */
  heatCost: number;
  /** Minimum cultists required to send */
  minCultists: number;
  /** Maximum cultists allowed */
  maxCultists: number;
  events: MissionEvent[];
}

export interface MissionEvent {
  id: string;
  text: string;
  choices: MissionChoice[];
}

export interface MissionChoice {
  label: string;
  skillCheck?: { skill: string; difficulty: number };
  outcomes: {
    success: {
      money?: number;
      influence?: number;
      prGain?: number;
      heatReduction?: number;
      decorItemId?: string;
      text: string;
    };
    failure: {
      money?: number;
      influence?: number;
      heatGain?: number;
      injuryChance?: number;
      text: string;
    };
  };
}

// ─── Mission Definitions ───────────────────────────────────────

export const MISSION_TEMPLATES: Record<string, MissionTemplate> = {
  // === Heat Reduction Missions ===

  propaganda_blitz: {
    id: 'propaganda_blitz',
    name: 'Propaganda Blitz',
    type: 'heat_reduction',
    description:
      'Send cultists into town to distribute flyers, post online, and spread good word about the compound. Reduces public suspicion.',
    duration: 6,
    difficulty: 3,
    rewards: { heatReduction: 30, prGain: 5 },
    heatCost: 2,
    minCultists: 2,
    maxCultists: 4,
    events: [
      {
        id: 'propaganda_blitz_event_1',
        text: 'A local journalist approaches your cultists asking for an interview about the compound.',
        choices: [
          {
            label: 'Give a charming interview',
            skillCheck: { skill: 'social', difficulty: 5 },
            outcomes: {
              success: {
                prGain: 10,
                heatReduction: 15,
                text: 'The interview goes viral and paints the cult in a positive light. Public sympathy rises.',
              },
              failure: {
                heatGain: 10,
                text: 'The interview goes poorly. The journalist twists your words and publishes a hit piece.',
              },
            },
          },
          {
            label: 'Decline politely and move on',
            outcomes: {
              success: {
                text: 'Your cultists politely decline and continue distributing flyers. No harm done.',
              },
              failure: {},
            },
          },
        ],
      },
    ],
  },

  community_service: {
    id: 'community_service',
    name: 'Community Service Outreach',
    type: 'heat_reduction',
    description:
      'Volunteer at local shelters, clean up parks, and help the elderly. The public will love us again.',
    duration: 8,
    difficulty: 2,
    rewards: { heatReduction: 25, prGain: 8, influence: 5 },
    heatCost: 0,
    minCultists: 3,
    maxCultists: 6,
    events: [
      {
        id: 'community_service_event_1',
        text: 'A grateful old woman offers your cultists a mysterious antique as thanks.',
        choices: [
          {
            label: 'Accept the gift graciously',
            skillCheck: { skill: 'social', difficulty: 3 },
            outcomes: {
              success: {
                decorItemId: 'antique_lamp',
                text: 'The old woman gives them a beautiful antique lamp. It will look wonderful in the compound.',
              },
              failure: {
                text: 'The cultists offend the woman by examining the lamp too critically. She shoos them away.',
              },
            },
          },
          {
            label: 'Politely decline — we are here to serve, not to receive',
            outcomes: {
              success: {
                prGain: 5,
                text: 'The selfless act is noticed by the community. Your reputation improves.',
              },
              failure: {},
            },
          },
        ],
      },
    ],
  },

  // === PR Generation Missions ===

  public_spectacle: {
    id: 'public_spectacle',
    name: 'Public Spectacle',
    type: 'pr_generation',
    description:
      'Stage a flashy public demonstration — fire dancing, chanting, and free snacks. Draw attention and new followers.',
    duration: 5,
    difficulty: 5,
    rewards: { prGain: 20, influence: 10, money: 50 },
    heatCost: 10,
    minCultists: 3,
    maxCultists: 5,
    events: [
      {
        id: 'public_spectacle_event_1',
        text: 'A rival cult shows up at the same park and starts competing for attention!',
        choices: [
          {
            label: 'Out-perform them with a dazzling display',
            skillCheck: { skill: 'faith', difficulty: 6 },
            outcomes: {
              success: {
                prGain: 15,
                influence: 10,
                text: 'Your cultists channel divine energy and put on a show that leaves the crowd awestruck. The rivals slink away.',
              },
              failure: {
                prGain: 5,
                heatGain: 15,
                text: 'The performance falls flat. The rival cult wins the crowd and your people look foolish. Heat rises.',
              },
            },
          },
          {
            label: 'Ignore them and focus on your own show',
            skillCheck: { skill: 'social', difficulty: 4 },
            outcomes: {
              success: {
                prGain: 10,
                text: 'Your cultists stay professional and win over a good portion of the crowd through sheer charm.',
              },
              failure: {
                heatGain: 5,
                text: 'The crowd is split and the event feels tense. A few onlookers file noise complaints.',
              },
            },
          },
        ],
      },
    ],
  },

  social_media_campaign: {
    id: 'social_media_campaign',
    name: 'Social Media Campaign',
    type: 'pr_generation',
    description:
      'Flood social media with positive content about the compound. Memes, testimonials, and cute cultist selfies.',
    duration: 4,
    difficulty: 4,
    rewards: { prGain: 15, influence: 5 },
    heatCost: 3,
    minCultists: 1,
    maxCultists: 3,
    events: [
      {
        id: 'social_media_event_1',
        text: 'A post goes viral — but it features a cultist accidentally revealing compound secrets in the background.',
        choices: [
          {
            label: 'Quickly delete and damage control',
            skillCheck: { skill: 'research', difficulty: 5 },
            outcomes: {
              success: {
                prGain: 10,
                text: 'The post is scrubbed before anyone notices. Crisis averted, and the other content is still performing well.',
              },
              failure: {
                heatGain: 20,
                text: 'The deletion is too slow. Screenshots circulate and conspiracy boards light up. Heat spikes.',
              },
            },
          },
          {
            label: 'Lean into it — claim it was intentional marketing',
            skillCheck: { skill: 'social', difficulty: 7 },
            outcomes: {
              success: {
                prGain: 25,
                text: 'The bold move pays off. People love the mystery and engagement skyrockets. New followers incoming!',
              },
              failure: {
                heatGain: 25,
                prGain: 0,
                text: 'Nobody buys it. The media picks up the story and scrutiny intensifies.',
              },
            },
          },
        ],
      },
    ],
  },

  // === Object Acquisition Missions ===

  antique_heist: {
    id: 'antique_heist',
    name: 'Antique Heist',
    type: 'object_acquisition',
    description:
      'A wealthy collector has a rare ornamental artifact. Send cultists to acquire it — discreetly.',
    duration: 10,
    difficulty: 7,
    rewards: { decorItemId: 'rare_artifact', influence: 15 },
    heatCost: 25,
    minCultists: 2,
    maxCultists: 4,
    events: [
      {
        id: 'antique_heist_event_1',
        text: 'A guard dog blocks the path to the display room. It looks hungry and mean.',
        choices: [
          {
            label: 'Distract it with food',
            skillCheck: { skill: 'social', difficulty: 4 },
            outcomes: {
              success: {
                text: 'The dog happily devours the snacks and falls asleep in a corner. Path is clear.',
              },
              failure: {
                injuryChance: 0.5,
                text: 'The dog is not impressed by the cheap snacks and attacks! A cultist is injured in the scuffle.',
              },
            },
          },
          {
            label: 'Sneak past it quietly',
            skillCheck: { skill: 'research', difficulty: 6 },
            outcomes: {
              success: {
                text: 'Your cultists move like shadows. The dog snores on, oblivious.',
              },
              failure: {
                heatGain: 15,
                injuryChance: 0.3,
                text: 'The dog wakes and barks wildly. Alarms may have been triggered. The cultists grab what they can and flee.',
              },
            },
          },
        ],
      },
      {
        id: 'antique_heist_event_2',
        text: 'The artifact is in a glass case with an electronic lock.',
        choices: [
          {
            label: 'Hack the lock',
            skillCheck: { skill: 'research', difficulty: 7 },
            outcomes: {
              success: {
                decorItemId: 'rare_artifact',
                text: 'The lock clicks open. The artifact is yours, clean and quiet.',
              },
              failure: {
                heatGain: 20,
                text: 'The hack fails and triggers a silent alarm. The cultists grab the artifact but must run!',
              },
            },
          },
          {
            label: 'Smash the glass and run',
            outcomes: {
              success: {
                decorItemId: 'rare_artifact',
                heatGain: 10,
                text: 'CRASH! The cultists grab the artifact and sprint. It is messy but effective.',
              },
              failure: {
                heatGain: 15,
                text: 'The glass is tougher than expected. They eventually get through but lose precious time.',
              },
            },
          },
        ],
      },
    ],
  },

  flea_market_run: {
    id: 'flea_market_run',
    name: 'Flea Market Run',
    type: 'object_acquisition',
    description:
      'The local flea market has cheap decor items — rugs, lamps, paintings. Send cultists to haggle for the good stuff.',
    duration: 4,
    difficulty: 2,
    rewards: { decorItemId: 'flea_market_treasure', money: 20 },
    heatCost: 5,
    minCultists: 1,
    maxCultists: 3,
    events: [
      {
        id: 'flea_market_event_1',
        text: 'A vendor has a gorgeous Persian rug, but the price is outrageous.',
        choices: [
          {
            label: 'Haggle aggressively',
            skillCheck: { skill: 'social', difficulty: 5 },
            outcomes: {
              success: {
                money: 50,
                decorItemId: 'persian_rug',
                text: 'The vendor caves and throws in a bonus lamp. What a steal!',
              },
              failure: {
                text: 'The vendor is offended and refuses to sell. Your cultists leave empty-handed on the rug front.',
              },
            },
          },
          {
            label: 'Just pay full price',
            outcomes: {
              success: {
                decorItemId: 'persian_rug',
                money: 0,
                text: 'The rug is expensive but gorgeous. It will boost compound prestige significantly.',
              },
              failure: {},
            },
          },
        ],
      },
    ],
  },

  // === Resource Gathering Missions ===

  fundraising_tour: {
    id: 'fundraising_tour',
    name: 'Fundraising Tour',
    type: 'resource_gathering',
    description:
      'Send cultists door-to-door and to local businesses soliciting donations for the compound.',
    duration: 7,
    difficulty: 4,
    rewards: { money: 150, influence: 10 },
    heatCost: 8,
    minCultists: 2,
    maxCultists: 5,
    events: [
      {
        id: 'fundraising_tour_event_1',
        text: 'A sympathetic business owner offers a large donation — but wants a favor in return.',
        choices: [
          {
            label: 'Agree to the favor (we will deal with it later)',
            skillCheck: { skill: 'social', difficulty: 5 },
            outcomes: {
              success: {
                money: 100,
                influence: 15,
                text: 'The cultists charm the business owner. The donation is generous and the favor seems minor.',
              },
              failure: {
                money: 20,
                heatGain: 10,
                text: 'The business owner feels uneasy about the cultists and gives a smaller donation. The favor is problematic.',
              },
            },
          },
          {
            label: 'Politely decline the favor and accept a smaller donation',
            outcomes: {
              success: {
                money: 50,
                text: 'The business owner respects the principle and gives a modest donation anyway.',
              },
              failure: {},
            },
          },
        ],
      },
    ],
  },

  supply_run: {
    id: 'supply_run',
    name: 'Supply Run',
    type: 'resource_gathering',
    description:
      'Drive to nearby towns to bulk-purchase food, materials, and everyday supplies at wholesale prices.',
    duration: 5,
    difficulty: 3,
    rewards: { money: 80, influence: 5 },
    heatCost: 3,
    minCultists: 1,
    maxCultists: 3,
    events: [
      {
        id: 'supply_run_event_1',
        text: 'The truck breaks down on the highway. The supplies are in the back, but time is ticking.',
        choices: [
          {
            label: 'Fix the truck on the side of the road',
            skillCheck: { skill: 'construction', difficulty: 5 },
            outcomes: {
              success: {
                money: 80,
                text: 'A cultist gets the engine running with a paperclip and duct tape. Legendary. The supplies arrive on time.',
              },
              failure: {
                money: 30,
                text: 'The repair takes hours. Some perishable supplies spoil in the heat. At least they make it back.',
              },
            },
          },
          {
            label: 'Hitchhike with the supplies',
            skillCheck: { skill: 'social', difficulty: 4 },
            outcomes: {
              success: {
                money: 70,
                text: 'A friendly trucker gives them a lift. They bond over classic rock and arrive safely with most supplies intact.',
              },
              failure: {
                money: 20,
                heatGain: 5,
                text: 'They find a ride with a nosy driver who asks too many questions about the compound. Heat ticks up slightly.',
              },
            },
          },
        ],
      },
    ],
  },
};

// ─── Helper Functions ──────────────────────────────────────────

/**
 * Get a mission template by its ID.
 */
export function getMissionTemplate(id: string): MissionTemplate | undefined {
  return MISSION_TEMPLATES[id];
}

/**
 * Get all mission templates as an array.
 */
export function getAllMissionTemplates(): MissionTemplate[] {
  return Object.values(MISSION_TEMPLATES);
}

/**
 * Get all mission templates of a specific type.
 */
export function getMissionsByType(type: MissionType): MissionTemplate[] {
  return Object.values(MISSION_TEMPLATES).filter((m) => m.type === type);
}